spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hand_?serverTimezone=GMT&useUnicode=true
    username: root
    password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml

logging:
  level:
    com.cmf: debug


